//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMashup.Core.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMashup.Core.I18n.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete your own User.
        /// </summary>
        public static string CannotDeleteYourOwnUser {
            get {
                return ResourceManager.GetString("CannotDeleteYourOwnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration cannot start or end outside the bounds of its Release.
        /// </summary>
        public static string IterationOutsideTheBoundsOfRelease {
            get {
                return ResourceManager.GetString("IterationOutsideTheBoundsOfRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Start and End dates of the Iteration, Iterations cannot be ovelaped in time.
        /// </summary>
        public static string IterationOverlapedErrorKey {
            get {
                return ResourceManager.GetString("IterationOverlapedErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Iterations in &quot;Planning&quot; state can be deleted.
        /// </summary>
        public static string OnlyIterationsInPlanningCanBeDeleted {
            get {
                return ResourceManager.GetString("OnlyIterationsInPlanningCanBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Releases in &quot;Planning&quot; state can be deleted.
        /// </summary>
        public static string OnlyReleasesInPlanningCanBeDeleted {
            get {
                return ResourceManager.GetString("OnlyReleasesInPlanningCanBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Start and End dates of the Release, Releases cannot be overlaped in time.
        /// </summary>
        public static string ReleaseOverlapedErrorKey {
            get {
                return ResourceManager.GetString("ReleaseOverlapedErrorKey", resourceCulture);
            }
        }
    }
}
