//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMashup.Core.I18n
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMashup.Core.I18n.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add with Details.
        /// </summary>
        public static string AddWithDetails {
            get {
                return ResourceManager.GetString("AddWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string AreYouSureYouWantToDelete {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to me.
        /// </summary>
        public static string AssignToMe {
            get {
                return ResourceManager.GetString("AssignToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burndown Chart.
        /// </summary>
        public static string BurndownChart {
            get {
                return ResourceManager.GetString("BurndownChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity in Story Points.
        /// </summary>
        public static string CapacityInStoryPoints {
            get {
                return ResourceManager.GetString("CapacityInStoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Issue.
        /// </summary>
        public static string CloseIssue {
            get {
                return ResourceManager.GetString("CloseIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commited.
        /// </summary>
        public static string Commited {
            get {
                return ResourceManager.GetString("Commited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Registration.
        /// </summary>
        public static string ConfirmRegistration {
            get {
                return ResourceManager.GetString("ConfirmRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new one.
        /// </summary>
        public static string CreateANewOne {
            get {
                return ResourceManager.GetString("CreateANewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Period.
        /// </summary>
        public static string CustomPeriod {
            get {
                return ResourceManager.GetString("CustomPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Started.
        /// </summary>
        public static string DateStarted {
            get {
                return ResourceManager.GetString("DateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined.
        /// </summary>
        public static string Defined {
            get {
                return ResourceManager.GetString("Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Story Points.
        /// </summary>
        public static string DefinedStoryPoints {
            get {
                return ResourceManager.GetString("DefinedStoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying Iterations for.
        /// </summary>
        public static string DisplayingIterationsFor {
            get {
                return ResourceManager.GetString("DisplayingIterationsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Story Points.
        /// </summary>
        public static string DoneStoryPoints {
            get {
                return ResourceManager.GetString("DoneStoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me this anymore.
        /// </summary>
        public static string DontShowMeThisAnymore {
            get {
                return ResourceManager.GetString("DontShowMeThisAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter issue summary.
        /// </summary>
        public static string EnterIssueSummary {
            get {
                return ResourceManager.GetString("EnterIssueSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Iteration name.
        /// </summary>
        public static string EnterIterationName {
            get {
                return ResourceManager.GetString("EnterIterationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Release name.
        /// </summary>
        public static string EnterReleaseName {
            get {
                return ResourceManager.GetString("EnterReleaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Bills.
        /// </summary>
        public static string HasPendingBills {
            get {
                return ResourceManager.GetString("HasPendingBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress Story Points.
        /// </summary>
        public static string InProgressStoryPoints {
            get {
                return ResourceManager.GetString("InProgressStoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Report.
        /// </summary>
        public static string IterationReport {
            get {
                return ResourceManager.GetString("IterationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Work.
        /// </summary>
        public static string LogWork {
            get {
                return ResourceManager.GetString("LogWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or you can.
        /// </summary>
        public static string OrYouCan {
            get {
                return ResourceManager.GetString("OrYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Capacity.
        /// </summary>
        public static string RealCapacity {
            get {
                return ResourceManager.GetString("RealCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Estimate.
        /// </summary>
        public static string RemainingEstimate {
            get {
                return ResourceManager.GetString("RemainingEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        public static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Plan.
        /// </summary>
        public static string SelectAPlan {
            get {
                return ResourceManager.GetString("SelectAPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Here.
        /// </summary>
        public static string StartHere {
            get {
                return ResourceManager.GetString("StartHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Points.
        /// </summary>
        public static string StoryPoints {
            get {
                return ResourceManager.GetString("StoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Active Release.
        /// </summary>
        public static string ThereIsNoActiveRelease {
            get {
                return ResourceManager.GetString("ThereIsNoActiveRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Spent.
        /// </summary>
        public static string TimeSpent {
            get {
                return ResourceManager.GetString("TimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributary Id.
        /// </summary>
        public static string TributaryId {
            get {
                return ResourceManager.GetString("TributaryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Chart.
        /// </summary>
        public static string VelocityChart {
            get {
                return ResourceManager.GetString("VelocityChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description.
        /// </summary>
        public static string WorkDescription {
            get {
                return ResourceManager.GetString("WorkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Projects.
        /// </summary>
        public static string YourProjects {
            get {
                return ResourceManager.GetString("YourProjects", resourceCulture);
            }
        }
    }
}
