//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMashup.Server.Areas.Public.Views.Home.i18n
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMashup.Server.Areas.Public.Views.Home.i18n.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Issues more quickly.
        /// </summary>
        public static string AddIssuesQuickly {
            get {
                return ResourceManager.GetString("AddIssuesQuickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just easy as drag and drop!.
        /// </summary>
        public static string ChangeIssueDragAndDrop {
            get {
                return ResourceManager.GetString("ChangeIssueDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Backlog.
        /// </summary>
        public static string ProjectBacklog {
            get {
                return ResourceManager.GetString("ProjectBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entirely Backlog is designed to allow you to create issues on the fly.
        /// </summary>
        public static string ProjectBacklogDescription {
            get {
                return ResourceManager.GetString("ProjectBacklogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Kanban.
        /// </summary>
        public static string ProjectKanban {
            get {
                return ResourceManager.GetString("ProjectKanban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the status of your tasks easily by just dragging and drop issues usin the Kanban.
        /// </summary>
        public static string ProjectKanbanDragAndDrop {
            get {
                return ResourceManager.GetString("ProjectKanbanDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan, work and get reports faster than ever with Team Mashup! Our interface is entirely designed thinking on going straight to the point. Register to create your Subscription now!.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalist Project Management.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
